### ISSUE TITLE
Wit.AI Integration

### ISSUE THREAD

**Issue by njoens** [meya-ai/community#14]
Meya currently supports **Intent** integration from the wit.ai platform by integrating your **Intent_Name** and **Accesss_token** from wit.ai

![wit_intent](https://cloud.githubusercontent.com/assets/13541378/14569302/77ff02e8-0303-11e6-90b5-75df0cd61629.PNG)

Wit.ai recently rolled out some updates to allow for a more intuitive system for working with bots specifically called [**Bot Engine**](https://wit.ai/blog/2016/04/12/bot-engine?hn)

As shown here, the old wit.ai console is built around **Intents**
![old wit](https://cloud.githubusercontent.com/assets/13541378/14569370/f62dea26-0303-11e6-8deb-e165a3acd898.PNG)

The new wit.ai console is built around **Stories**, which are example conversations that you might have with your bot. **Intents** are completely removed as they were merged with **Entities** under the **Understanding** tab in the new console. 
![new wit](https://cloud.githubusercontent.com/assets/13541378/14569402/3075cad2-0304-11e6-8ce3-d7d46cb5fffe.PNG)

The documentation for wit.ai has also been updated to accommodate the new features [https://wit.ai/docs/quickstart](https://wit.ai/docs/quickstart) 

Meya.ai should reflect the updated wit.ai console to support **Stories** and **Understanding**

**Comment by eljun** [comment]
Hello Sir the url 'https://wit.ai/docs/quickstart' doesn't work. Please check.

**Comment by ekalvi** [comment]
Fixed.

**Comment by ekalvi** [comment]
We've added expanded support for wit.ai (**Understanding**), however, we have not yet implemented the **Stories** API. Can someone provide a use-case that isn't covered by Meya's core flow feature set? Why would you want to write a Wit.ai story and connect to Meya?

See the launch announcement: http://docs.meya.ai/blog/v12-launch-improved-nlp-conditionals-user-profiles

**Comment by ekalvi** [comment]
We have no reason to support Stories, so therefore closing this issue.
