### ISSUE TITLE
Cron jobs?

### ISSUE THREAD

**Issue by milesmatthias** [meya-ai/community#15]
I looked pretty quickly, but I didn't see any cron job-type support. Are daily messages or questions behavior supported?

_I also don't think I have permissions to add the question label..._

**Comment by ekalvi** [comment]
We will be supporting periodic events soon likely as a built-in component `meya.schedule` which invokes a transition based on the periodicity properties you specify in the flow.

**Comment by ekalvi** [comment]
Launched: http://docs.meya.ai/blog/clockwork-like-timing-with-meya-scheduling
