### ISSUE TITLE
How to get the phone number of the user when using Twilio integration ?

### ISSUE THREAD

**Issue by Uelb** [meya-ai/community#16]

**Comment by ekalvi** [comment]
Not possible yet.

We're working on automatically populating user profile information in the user db. You'll be able to access their phone number via something like `self.db.user.get('phone_number')`.

We will ping this thread when possible.

**Comment by ekalvi** [comment]
This is now available. You can get the Twilio's phone number either by:
1. `self.db.user.user_id`
2. `sef.db.user.get('phone')

Method 1 is preferred since it's immutable. You can change the value for the user's phone in method 2.
