### ISSUE TITLE
Messaging Platform Debug

### ISSUE THREAD

**Issue by russellmiller3** [meya-ai/community#18]
Sometimes there are hiccups between Facebook and Meya, and it'd be useful to have those logged to see what's happening.  Probably a similar situation with other platforms

**Comment by russellmiller3** [comment]
background: I'm doing user testing and users will say that bot is unresponsive on Fb sometimes but I don't have a way to see what happened.

**Comment by ekalvi** [comment]
What frequency were the outages? What specific times? You can send via Slack DM or erik@meya.ai

**Comment by russellmiller3** [comment]
I'll look in my logs and see if i can find the times
