### ISSUE TITLE
Emoji support in messages

### ISSUE THREAD

**Issue by russellmiller3** [meya-ai/community#19]
A nice to have.  
See [http://atwherebot.com/]

**Comment by russellmiller3** [comment]
See here: [http://apps.timwhitlock.info/emoji/tables/unicode]

**Comment by ekalvi** [comment]
We support emoji in messages, however only via the unicode representation. Pasting emoji directly isn't supported and a known bug. In YAML:

```yaml
name: greeting
states:
    greeting:
        component: meya.random_text
        properties:
            responses:
            - "Hey there! \U0001F604"
            - "Hi! \U0001F604"
            - "Howdy! \U0001F604"
        delay:
            relative: 1
    help:
        component: meya.text
        properties:
            text: How can I help you today?
```

<img width="356" alt="screen shot 2016-07-13 at 6 20 36 pm" src="https://cloud.githubusercontent.com/assets/1478414/16821836/8a1b69da-4926-11e6-9722-ebd7c6c03e01.png">

**Comment by russellmiller3** [comment]
Ah, thanks Erik!
ᐧ

**Comment by russellmiller3** [comment]
it looks like this workaround is fine for text and buttons, but not for
buttons in components.
An extra backslash is being added.


[image: Inline image 1]

ᐧ

**Comment by ekalvi** [comment]
In Python code, you can use the native emoji character specify the string as unicode:
```python
text = u"Hey there! \U0001F604"
```

**Comment by russellmiller3** [comment]
Ok, I'm seeing odd behavior when I try that.

[image: Inline image 1]
ᐧ

**Comment by ekalvi** [comment]
This works for me. Do you have the utf-8 line at the top?

```python
# -*- coding: utf-8 -*-
from meya import Component


class EmojiComponent(Component):
    def start(self):
        messages = [
            self.create_message(text=u"Hi there! 😀"),
            self.create_message(text=u"Ho there! \U0001F604")
        ]
        return self.respond(messages=messages, action="next")
```

<img width="356" alt="screen shot 2016-07-13 at 9 04 31 pm" src="https://cloud.githubusercontent.com/assets/1478414/16824880/6d15ded0-493d-11e6-8846-c92ef416ca45.png">

**Comment by russellmiller3** [comment]
I didn't have the utf line there, but I added it and I'm still seeing the
strange behavior.
component attached.

ᐧ

**Comment by ekalvi** [comment]
This has been fixed with the Meya Studio release in October, 2016.
