### ISSUE TITLE
Facebook: Card missing forward icon

### ISSUE THREAD

**Issue by russellmiller3** [meya-ai/community#25]
Cards in Meya seem to be missing the forward icon in Facebook that other chatbots show.

![missing](https://cloud.githubusercontent.com/assets/6886512/16811401/f3a7b812-48dc-11e6-89b8-c3d720bc6fee.jpg)

**Comment by ekalvi** [comment]
This is not set by integration. Messenger automatically adds the forward icon on certain media types.
