### ISSUE TITLE
Webhook: meya.video component renders as text

### ISSUE THREAD

**Issue by giorgiomarzianidepaolis-was** [meya-ai/community#31]
The `meya.video` component sends to the output webhook API a standard text message with just URL in text.
I think `type` should be `"type": "video"` instead of `"type": "text"`.

**Comment by ekalvi** [comment]
This was released Oct. 13, 2016 with support for `meya.cards`, `meya.receipt`, `meya.video`, `meya.audio`, `meya.file`. The type will be set to `cards`, `video` etc. and will have a payload similar to `meya.image` and other cards.

**Comment by indrax** [comment]
Kings @bye

**Comment by indrax** [comment]
King @by3
