### ISSUE TITLE
Connecting to multiple FB pages

### ISSUE THREAD

**Issue by adboio** [meya-ai/community#33]
Is there a way to connect a bot to multiple FB pages w/ the current messenger integration?

**Comment by ekalvi** [comment]
Not at the moment. Do you mind sharing the use-case?

**Comment by bissolli** [comment]
Any news on this feature?

**Comment by ekalvi** [comment]
No news. Same question: Can you share the use-case?

**Comment by adboio** [comment]
Sorry, didn't see your message first. I work for what is essentially a social media marketing company and we have hundreds of FB pages, one for each city we operate in. Each one needs the same bot, but we didn't have time to create hundreds of bots. We ended up going a different route with it but this would still be great functionality!

**Comment by ekalvi** [comment]
Got it. There is an approach where bots can share code using GitHub auto-syncing. That being said, we'll consider this for a future release.
